cd /gpfs/home/guosa/hpc/rheumatology/SLE/BCR/vdj
mkdir temp
for i in $(cat fq.txt)
do
echo \#PBS -N $i  > $i.job
echo \#PBS -l nodes=1:ppn=1 >> $i.job
echo \#PBS -M Guo.shicheng\@marshfieldresearch.org >> $i.job
echo \#PBS -m abe  >> $i.job
echo \#PBS -o $(pwd)/temp/ >>$i.job
echo \#PBS -e $(pwd)/temp/ >>$i.job
echo cd $(pwd) >> $i.job
echo flash2 -m 2 -M 200 $i\_R1.fq $i\_R1.fq -o $i.fq >>$i.job
qsub $i.job
done
